-- Add provider_message_id to message table for idempotency
ALTER TABLE message ADD COLUMN provider_message_id VARCHAR(255);

-- H2 ne supporte pas les "partial indexes" (WHERE ...).
-- Un UNIQUE INDEX standard suffit: PostgreSQL et H2 autorisent plusieurs NULL
-- et empêchent les doublons non-nuls.
CREATE UNIQUE INDEX idx_message_provider_message_id ON message(provider_message_id);

-- Create whatsapp_provider_config table
-- BIGSERIAL est spécifique PostgreSQL, on utilise BIGINT + IDENTITY (compatible H2 et PostgreSQL récents).
CREATE TABLE whatsapp_provider_config (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id VARCHAR(255) NOT NULL,
    api_key_encrypted TEXT NOT NULL,
    api_secret_encrypted TEXT NOT NULL,
    webhook_secret_encrypted TEXT NOT NULL,
    phone_number_id VARCHAR(255) NOT NULL,
    business_account_id VARCHAR(255),
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_whatsapp_provider_config_org_id UNIQUE (org_id)
);

CREATE INDEX idx_whatsapp_provider_config_org_id ON whatsapp_provider_config(org_id);
