package com.example.backend.entity.enums;

public enum ActivityType {
    NOTE,
    STATUS_CHANGE,
    APPOINTMENT_CREATED,
    APPOINTMENT_SCHEDULED,
    APPOINTMENT_COMPLETED,
    MESSAGE_SENT,
    MESSAGE_FAILED,
    CONSENT_GRANTED,
    CONSENT_REVOKED,
    CONSENT_RENEWED
}
