package com.example.backend.entity.enums;

public enum ActivityType {
    NOTE,
    STATUS_CHANGE,
    APPOINTMENT_CREATED,
    APPOINTMENT_SCHEDULED,
    APPOINTMENT_COMPLETED,
    MESSAGE_SENT,
    MESSAGE_FAILED,
    CONSENT_GRANTED,
    CONSENT_REVOKED,
    CONSENT_RENEWED,
    CONVERSATION_STARTED,
    CONVERSATION_REPLY,
    APPOINTMENT_CONFIRMED,
    APPOINTMENT_CANCELLED_BY_CLIENT,
    APPOINTMENT_RESCHEDULED_BY_CLIENT
}
